apiVersion: apps/v1
kind: Deployment
metadata:
  name: raster-worker
  labels:
    ellipsis-drive: raster-worker
spec:
  replicas: 0
  selector:
    matchLabels:
      ellipsis-drive: raster-worker
  template:
    metadata:
      labels:
        ellipsis-drive: raster-worker
    spec:
      containers:
      - name: raster-worker
        image: ghcr.io/ellipsis-drive/raster-worker:latest
        resources:
          requests:
            cpu: 4
            memory: 32Gi
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        envFrom:
          - configMapRef:
              name: ellipsis
        volumeMounts:
          - name: etmpfs
            mountPath: /mnt/etmpfs
          - name: tmpfs
            mountPath: /mnt/tmpfs  
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      volumes:
        - name: etmpfs
          persistentVolumeClaim:
            claimName: etmpfs
        - name: tmpfs
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi