apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket
  labels:
    ellipsis-drive: socket
spec:
  replicas: 2
  selector:
    matchLabels:
      ellipsis-drive: socket
  template:
    metadata:
      labels:
        ellipsis-drive: socket
    spec:
      containers:
      - name: socket
        image: ghcr.io/ellipsis-drive/socket:latest
        resources:
          requests:
            cpu: 500m
        ports:
          - containerPort: 7754
        envFrom:
          - configMapRef:
              name: ellipsis
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
          - name: POSTGRES_APP_PASS_LOCAL
            valueFrom:
              secretKeyRef:
                name: pigeon-db-password
                key: password
          - name: API_TO_PYTHON_HANDSHAKE
            valueFrom:
              secretKeyRef:
                name: pigeon-socket-handshake
                key: api
          - name: PYTHON_TO_API_HANDSHAKE
            valueFrom:
              secretKeyRef:
                name: pigeon-socket-handshake
                key: python
          - name: NUMBER_OF_API_PROCESSES
            value: "2"
        volumeMounts:
          - name: etmpfs
            mountPath: /mnt/etmpfs
          - name: finch-1
            mountPath: /mnt/finch
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: etmpfs
          persistentVolumeClaim:
            claimName: etmpfs
        - name: finch-1
          persistentVolumeClaim:
            claimName: finch-1