apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rooster-1-list-features
  labels:
    ellipsis-drive: rooster-1-list-features
spec:
  serviceName: rooster-1-list-features
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: rooster-1-list-features
  template:
    metadata:
      labels:
        ellipsis-drive: rooster-1-list-features
    spec:
      securityContext:
        fsGroup: 1623
        runAsGroup: 1623
        runAsNonRoot: true
        runAsUser: 1623
      containers:
        - name: rooster-1-list-features
          image: ghcr.io/ellipsis-drive/file-server-api-vector:1.0.0
          resources:
            requests:
              cpu: 500m
          ports:
            - containerPort: 8738
          envFrom:
          - configMapRef:
              name: ellipsis
          volumeMounts:
            - name: rooster-1-list-features-db
              mountPath: /mnt/listFeatures
      imagePullSecrets:
        - name: ghcr-secret
  volumeClaimTemplates:
    - metadata:
        name: rooster-1-list-features-db
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ebs-sc
        resources:
          requests:
            storage: 10Gi
