apiVersion: v1
kind: Secret
metadata:
  name: owl-db-password
type: Opaque
stringData:
  password: foobar
---
apiVersion: v1
kind: Secret
metadata:
  name: rooster-db-password
type: Opaque
stringData:
  password: foobar