apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-management-deployment
  labels:
    ellipsis-drive: oauth-management
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: oauth-management
  template:
    metadata:
      labels:
        ellipsis-drive: oauth-management
    spec:
      containers:
      - name: oauth-management
        image: ghcr.io/ellipsis-drive/oauth-management:latest
        resources:
          requests:
            cpu: 250m
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
          - name: INTERNAL_MAIL
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: username
          - name: INTERNAL_MAIL_PASS
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: password
        envFrom:
          - configMapRef:
              name: ellipsis
      imagePullSecrets:
        - name: dockerconfigjson-github-com