apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-monitor-deployment
  labels:
    ellipsis-drive: subscription-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: subscription-monitor
  template:
    metadata:
      labels:
        ellipsis-drive: subscription-monitor
    spec:
      containers:
      - name: subscription-monitor
        image: ghcr.io/ellipsis-drive/subscription-monitor:latest
        # resources:
        #   requests:
        #     cpu: 250m
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
          - name: INTERNAL_MAIL
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: username
          - name: INTERNAL_MAIL_PASS
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: password
        envFrom:
          - configMapRef:
              name: ellipsis
      imagePullSecrets:
        - name: dockerconfigjson-github-com