apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-system-management
  labels:
    ellipsis-drive: file-system-management
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: file-system-management
  template:
    metadata:
      labels:
        ellipsis-drive: file-system-management
    spec:
      serviceAccountName: s3-access-sa
      containers:
      - name: file-system-management
        image: ghcr.io/ellipsis-drive/file-system-management:latest
        resources:
          requests:
            cpu: 100m
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
          - name: INTERNAL_MAIL
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: username
          - name: INTERNAL_MAIL_PASS
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: password
        envFrom:
          - configMapRef:
              name: ellipsis
        volumeMounts:
          - name: etmpfs
            mountPath: /mnt/etmpfs
          - name: finch-1
            mountPath: /mnt/finch-1-eu-central-1
      imagePullSecrets:
        - name: ghcr-secret

      volumes:
        - name: etmpfs
          persistentVolumeClaim:
            claimName: etmpfs
        - name: finch-1
          persistentVolumeClaim:
            claimName: finch-1