apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    ellipsis-drive: api
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: api
  template:
    metadata:
      labels:
        ellipsis-drive: api
    spec:
      containers:
      - name: api
        image: ghcr.io/ellipsis-drive/api:latest
        ports:
          - containerPort: 7556
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
          - name: POSTGRES_APP_PASS_SHAPE
            valueFrom:
              secretKeyRef:
                name: rooster-db-password
                key: password
        envFrom:
          - configMapRef:
              name: ellipsis
        volumeMounts:
          - name: etmpfs
            mountPath: /mnt/etmpfs
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      volumes:
        - name: etmpfs
          persistentVolumeClaim:
            claimName: etmpfs