apiVersion: apps/v1
kind: Deployment
metadata:
  name: finch-file-server-api
  labels:
    ellipsis-drive: finch-file-server-api
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: finch-file-server-api
  template:
    metadata:
      labels:
        ellipsis-drive: finch-file-server-api
    spec:
      containers:
      - name: finch-file-server-api
        image: ghcr.io/ellipsis-drive/finch-file-server-api:latest
        envFrom:
          - configMapRef:
              name: ellipsis
        volumeMounts:
          - name: finch-1-fra
            mountPath: /mnt/fileserver
      imagePullSecrets:
        - name: dockerconfigjson-github-com

      volumes:
        - name: finch-1-fra
          persistentVolumeClaim:
            claimName: finch-1-fra