apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: finch-file-server-api
  labels:
    ellipsis-drive: finch-file-server-api
spec:
  serviceName: finch-file-server-api
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: finch-file-server-api
  template:
    metadata:
      labels:
        ellipsis-drive: finch-file-server-api
    spec:
      containers:
        - name: finch-file-server-api
          image: ghcr.io/ellipsis-drive/finch-file-server-api:latest
          ports:
            - containerPort: 8738
          volumeMounts:
            - name: finch-fileserver
              mountPath: /mnt/fileserver
          envFrom:
            - configMapRef:
                name: ellipsis
      imagePullSecrets:
        - name: ghcr-secret
  volumeClaimTemplates:
    - metadata:
        name: finch-fileserver
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ebs-sc
        resources:
          requests:
            storage: 10Gi