services:
  api:
    build:
      context: ./api
      dockerfile: api.dockerfile
    env_file: "./ellipsis.env"
    networks:
      - api-network
    restart: unless-stopped
    volumes:
      - ./shared:/mnt/shared
    depends_on:
      cache_db:
        condition: service_started
    ports:
      - "7556:7556"

  cache_db:
    environment:
      - POSTGRES_USER=local_api
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_cache
    build: .
    networks:
      - api-network
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgres

  socket:
    build:
      context: ./python
      dockerfile: socket.dockerfile
    env_file: "./ellipsis.env"
    networks:
      - api-network
    restart: unless-stopped

  invalidator:
    build:
      context: ./api
      dockerfile: invalidator.dockerfile
    env_file: "./ellipsis.env"
    networks:
      - api-network
    restart: unless-stopped
    depends_on:
      cache_db:
        condition: service_started


networks:
  api-network:
    driver: bridge