apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-writer
  labels:
    ellipsis-drive: actions-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: actions-writer
  template:
    metadata:
      labels:
        ellipsis-drive: actions-writer
    spec:
      containers:
      - name: actions-writer
        image: ghcr.io/ellipsis-drive/actions-writer:latest
        resources:
          requests:
            cpu: 50m
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
          - name: POSTGRES_APP_PASS_LOCAL
            valueFrom:
              secretKeyRef:
                name: pigeon-db-password
                key: password
          - name: INTERNAL_MAIL
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: username
          - name: INTERNAL_MAIL_PASS
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: password
        envFrom:
          - configMapRef:
              name: ellipsis
      imagePullSecrets:
        - name: ghcr-secret