apiVersion: apps/v1
kind: Deployment
metadata:
  name: export-master
  labels:
    ellipsis-drive: export-master
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: export-master
  template:
    metadata:
      labels:
        ellipsis-drive: export-master
    spec:
      serviceAccountName: cluster-master-service-account
      containers:
      - name: export-master
        image: ghcr.io/ellipsis-drive/export-master:latest
        # resources:
        #   requests:
        #     cpu: 500m
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
          - name: MIN_WORKERS
            value: "0"
          - name: MAX_WORKERS
            value: "2"
          - name: INTERNAL_MAIL
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: username
          - name: INTERNAL_MAIL_PASS
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: password
        envFrom:
          - configMapRef:
              name: ellipsis
        volumeMounts:
          - name: etmpfs
            mountPath: /mnt/etmpfs
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: etmpfs
          persistentVolumeClaim:
            claimName: etmpfs