apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: owl
  labels:
    ellipsis-drive: owl
spec:
  serviceName: owl
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: owl
  template:
    metadata:
      labels:
        ellipsis-drive: owl
    spec:
      containers:
        - name: owl
          image: ghcr.io/ellipsis-drive/owl:latest
          resources:
            requests:
              cpu: 500m
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owl-db-password
                  key: password
            - name: PGDATA
              value: /mnt/db/pgdata
          args:
            - "-c"
            - "config_file=/etc/postgres-config/postgresql.conf"
            - "-c"
            - "hba_file=/etc/postgres-config/pg_hba.conf"
          volumeMounts:
            - name: postgres-config
              mountPath: /etc/postgres-config
            - name: owl-db-2
              mountPath: /mnt/db
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: postgres-config
          configMap:
            name: owl-postgres-config
  volumeClaimTemplates:
    - metadata:
        name: owl-db-2
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ebs-sc-2
        resources:
          requests:
            storage: 10Gi
