apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooster-1-list-features-deployment
  labels:
    ellipsis-drive: rooster-1-list-features
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: rooster-1-list-features
  template:
    metadata:
      labels:
        ellipsis-drive: rooster-1-list-features
    spec:
      containers:
      - name: rooster-1-list-features
        image: ghcr.io/ellipsis-drive/file-server-api-vector:latest
        ports:
          - containerPort: 8738
        env:
          - name: INTERNAL_MAIL
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: username
          - name: INTERNAL_MAIL_PASS
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: password
        envFrom:
          - configMapRef:
              name: ellipsis
      imagePullSecrets:
        - name: dockerconfigjson-github-com
