apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-path-rename
  labels:
    ellipsis-drive: process-path-rename
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: process-path-rename
  template:
    metadata:
      labels:
        ellipsis-drive: process-path-rename
    spec:
      containers:
      - name: process-path-rename
        image: ghcr.io/ellipsis-drive/process-path-rename:latest
        resources:
          requests:
            cpu: 50m
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
          - name: INTERNAL_MAIL
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: username
          - name: INTERNAL_MAIL_PASS
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: password
        envFrom:
          - configMapRef:
              name: ellipsis
      imagePullSecrets:
        - name: ghcr-secret