apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-finch-1-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-finch-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-025868a603a94e11d