apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-raster-bounds-deployment
  labels:
    ellipsis-drive: create-raster-bounds
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: create-raster-bounds
  template:
    metadata:
      labels:
        ellipsis-drive: create-raster-bounds
    spec:
      containers:
      - name: create-raster-bounds
        image: ghcr.io/ellipsis-drive/create-raster-bounds:latest
        resources:
          requests:
            cpu: 1
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
        envFrom:
          - configMapRef:
              name: ellipsis
        volumeMounts:
          - name: etmpfs
            mountPath: /mnt/etmpfs
      imagePullSecrets:
        - name: dockerconfigjson-github-com

      volumes:
        - name: etmpfs
          persistentVolumeClaim:
            claimName: etmpfs