apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-system-management-deployment
  labels:
    ellipsis-drive: file-system-management
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: file-system-management
  template:
    metadata:
      labels:
        ellipsis-drive: file-system-management
    spec:
      serviceAccountName: s3-access-sa
      containers:
      - name: file-system-management
        image: ghcr.io/ellipsis-drive/file-system-management:latest
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
        envFrom:
          - configMapRef:
              name: ellipsis
        volumeMounts:
          - name: etmpfs
            mountPath: /mnt/etmpfs
      imagePullSecrets:
        - name: dockerconfigjson-github-com

      volumes:
        - name: etmpfs
          persistentVolumeClaim:
            claimName: etmpfs