apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnails-deployment
  labels:
    ellipsis-drive: thumbnails
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: thumbnails
  template:
    metadata:
      labels:
        ellipsis-drive: thumbnails
    spec:
      containers:
      - name: thumbnails
        image: ghcr.io/ellipsis-drive/thumbnails:latest
        resources:
          requests:
            cpu: 1
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
          - name: INTERNAL_MAIL
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: username
          - name: INTERNAL_MAIL_PASS
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: password
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: secret
                key: secret
        envFrom:
          - configMapRef:
              name: ellipsis
      imagePullSecrets:
        - name: dockerconfigjson-github-com