apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    ellipsis-drive: api
spec:
  replicas: 2
  selector:
    matchLabels:
      ellipsis-drive: api
  template:
    metadata:
      labels:
        ellipsis-drive: api
    spec:
      serviceAccountName: s3-access-sa
      containers:
      - name: api
        image: ghcr.io/ellipsis-drive/api:1.0.0
        resources:
          requests:
            cpu: 500m
        ports:
          - containerPort: 7556
        envFrom:
          - configMapRef:
              name: ellipsis
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
          - name: POSTGRES_APP_PASS_LOCAL
            valueFrom:
              secretKeyRef:
                name: pigeon-db-password
                key: password
          - name: POSTGRES_APP_PASS_SHAPE
            valueFrom:
              secretKeyRef:
                name: rooster-db-password
                key: password
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: secret
                key: secret
          - name: OAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth-secret
                key: secret
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: google-client
                key: id
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google-client
                key: secret
          - name: ELLIPSIS_INTERNAL_KEY_GET_CACHE
            valueFrom:
              secretKeyRef:
                name: ellipsis-internal-key
                key: get-cache
          - name: ELLIPSIS_INTERNAL_KEY_POINT_CLOUD
            valueFrom:
              secretKeyRef:
                name: ellipsis-internal-key
                key: point-cloud
          - name: ELLIPSIS_INTERNAL_KEY_PROCESS
            valueFrom:
              secretKeyRef:
                name: ellipsis-internal-key
                key: process
          - name: ELLIPSIS_INTERNAL_KEY_RASTER
            valueFrom:
              secretKeyRef:
                name: ellipsis-internal-key
                key: raster
          - name: ELLIPSIS_INTERNAL_KEY_REDIRECT
            valueFrom:
              secretKeyRef:
                name: ellipsis-internal-key
                key: redirect
          - name: ELLIPSIS_INTERNAL_KEY_SANITY_VECTOR
            valueFrom:
              secretKeyRef:
                name: ellipsis-internal-key
                key: sanity-vector
          - name: ELLIPSIS_INTERNAL_KEY_VECTOR
            valueFrom:
              secretKeyRef:
                name: ellipsis-internal-key
                key: vector
          - name: INTERNAL_MAIL
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: username
          - name: INTERNAL_MAIL_PASS
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: password
        volumeMounts:
          - name: etmpfs
            mountPath: /mnt/etmpfs
          - name: finch-1
            mountPath: /mnt/finch
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: etmpfs
          persistentVolumeClaim:
            claimName: etmpfs
        - name: finch-1
          persistentVolumeClaim:
            claimName: finch-1