apiVersion: apps/v1
kind: Deployment
metadata:
  name: invalidator-deployment
  labels:
    ellipsis-drive: invaldiator
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: invalidator
  template:
    metadata:
      labels:
        ellipsis-drive: invalidator
    spec:
      containers:
      - name: invalidator
        image: ghcr.io/ellipsis-drive/invalidator:latest
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
        envFrom:
          - configMapRef:
              name: ellipsis
      imagePullSecrets:
        - name: dockerconfigjson-github-com
