apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: owl
  labels:
    ellipsis-drive: owl
spec:
  instances: 3
  imageName: ghcr.io/ellipsis-drive/owl:18

  imagePullSecrets:
  - name: ghcr-secret

  storage:
    size: 10Gi
    storageClass: ebs-sc

  bootstrap:
    initdb:
      database: ellipsis
      owner: ellipsis_app
      secret:
        name: owl-db-password
      postInitApplicationSQLRefs:
        configMapRefs:
        - name: owl-init-database
          key: database.sql
        - name: owl-data-database
          key: queries.sql
        - name: icons-init-database
          key: queries.sql

  resources:
    requests:
      memory: "1024Mi"
      cpu: 1
    limits:
      memory: "1024Mi"
      cpu: 1

  priorityClassName: high-priority