apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-history-appender-deployment
  labels:
    ellipsis-drive: user-history-appender
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: user-history-appender
  template:
    metadata:
      labels:
        ellipsis-drive: user-history-appender
    spec:
      containers:
      - name: user-history-appender
        image: ghcr.io/ellipsis-drive/user-history-appender:latest
        resources:
          requests:
            cpu: 250m
        env:
          - name: POSTGRES_APP_PASS
            valueFrom:
              secretKeyRef:
                name: owl-db-password
                key: password
          - name: INTERNAL_MAIL
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: username
          - name: INTERNAL_MAIL_PASS
            valueFrom:
              secretKeyRef:
                name: internal-mail
                key: password
        envFrom:
          - configMapRef:
              name: ellipsis
      imagePullSecrets:
        - name: dockerconfigjson-github-com