apiVersion: v1
kind: Secret
metadata:
  name: owl-db-password
type: Opaque
stringData:
  username: ellipsis_app
  password: foobar
---
apiVersion: v1
kind: Secret
metadata:
  name: rooster-db-password
type: Opaque
stringData:
  username: ellipsis_app
  password: foobar
---
apiVersion: v1
kind: Secret
metadata:
  name: pigeon-db-password
type: Opaque
stringData:
  username: local_api
  password: foobar
---
apiVersion: v1
kind: Secret
metadata:
  name: pigeon-socket-handshake
type: Opaque
stringData:
  api: foobar
  python: foobar
---
apiVersion: v1
kind: Secret
metadata:
  name: ellipsis-internal-key
type: Opaque
stringData:
  get-cache: foobar
  point-cloud: foobar
  process: foobar
  raster: foobar
  redirect: foobar
  sanity-vector: foobar
  vector: foobar
---
apiVersion: v1
kind: Secret
metadata:
  name: google-client
type: Opaque
stringData:
  id: foobar
  secret: foobar
---
apiVersion: v1
kind: Secret
metadata:
  name: internal-mail
type: Opaque
stringData:
  username: internal@ellipsis-drive.com
  password: foobar
---
apiVersion: v1
kind: Secret
metadata:
  name: noreply-mail
type: Opaque
stringData:
  username: no-reply@ellipsis-drive.com
  password: foobar
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  secret: foobar
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-secret
type: Opaque
stringData:
  secret: foobar