apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-db
  labels:
    ellipsis-drive: cache-db
spec:
  replicas: 1
  selector:
    matchLabels:
      ellipsis-drive: cache-db
  template:
    metadata:
      labels:
        ellipsis-drive: cache-db
    spec:
      containers:
      - name: cache-db
        image: ghcr.io/ellipsis-drive/cache-db:latest
        resources:
          requests:
            cpu: 200m
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: ellipsis
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pigeon-db-password
                key: password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: ellipsis
                key: POSTGRES_DB_LOCAL
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: ellipsis
                key: POSTGRES_USER_LOCAL
      imagePullSecrets:
        - name: ghcr-secret
